### ISSUE TITLE
libOpenGL.so.0 and libGLX.so.0 errors

### ISSUE THREAD

**Issue by Greelan** [rollerozxa/luanti-appimage#1]
I get the error `error while loading shared libraries: libOpenGL.so.0: cannot open shared object file: No such file or directory` when trying the run the server (I've extracted the image and am running `luanti` directly). I've add the lib path to `LD_LIBRARY_PATH`. Any suggestions?

**Comment by Greelan** [comment]
After "fixing" this by installing `libopengl0` then I get the same error that `libGLX.so.0` can't be found

**Comment by rollerozxa** [comment]
The AppImage requires you to have OpenGL libraries installed since it's supposed to be a client build and it is assumed you're in a graphical environment where this is already provided. And I also can't bundle them because I wouldn't know if you need Mesa, the proprietary Nvidia drivers or AMDGPU-PRO.

If you want to run a headless server and I assume you do not have a graphical environment set up, you would probably want my [dedicated luantiserver Linux builds](https://forum.luanti.org/viewtopic.php?p=440492#p440492) which don't have all of the dependencies that the client has since it's just the headless server.

**Comment by Greelan** [comment]
Thanks, headless server is what I am after.

Have you run it also on non-Debian-based distros?

**Comment by Greelan** [comment]
My question is essentially: how portable is this?

And if the build is effectively cross-distro, why don't the Luanti devs make such a release available themselves?
